---
- name: Ensure paste paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ paste_uid }}"
    group: "{{ paste_gid }}"
  with_items:
    - "{{ paste_base_path }}"

- name: Ensure paste support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ paste_base_path }}/{{ item }}"
    mode: 0640
    owner: "{{ paste_uid }}"
    group: "{{ paste_gid }}"
  with_items:
    - env
    - labels

- name: Ensure paste container image is pulled
  community.docker.docker_image:
    name: "{{ paste_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ paste_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else paste_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure paste container network is created
  community.general.docker_network:
    name: "{{ paste_container_network }}"
    driver: bridge

- name: Ensure paste systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/paste.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ paste_identifier }}.service"
    mode: 0644
