---
- name: Check existence of paste systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ paste_identifier }}.service"
  register: paste_service_stat

- when: paste_service_stat.stat.exists | bool
  block:
    - name: Ensure paste systemd service is stopped
      ansible.builtin.service:
        name: "{{ paste_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure paste systemd service does not exists
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ paste_identifier }}.service"
        state: absent

    - name: Ensure paste path doesn't exist
      ansible.builtin.file:
        path: "{{ paste_base_path }}"
        state: absent
