---
- name: Fail if required paste settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - paste_identifier
    - paste_uid
    - paste_gid
    - paste_hostname
    - paste_path_prefix
    - paste_container_network
    - paste_database_hostname
    - paste_database_password

- when: paste_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required paste Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - paste_container_labels_traefik_hostname
        - paste_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `paste_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if paste_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          paste_container_labels_traefik_path_prefix (`{{ paste_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/paste`).
      when: "paste_container_labels_traefik_path_prefix != '/' and paste_container_labels_traefik_path_prefix[-1] == '/'"
